### ISSUE TITLE
Single file compilation

### ISSUE THREAD

**Issue by Stefanuk12** [valencefun/unluau#23]
When you compile the CLI, it has many dependencies which is an issue when releasing (as seen in the latest release), consider reading the following article on publishing as a single file: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli

Note: I will make a PR soon implementing this, feel free to deny or accept it

**Comment by asmlore** [comment]
Thank you. Looking forward to reviewing your pull request.

**Comment by Stefanuk12** [comment]
I was not able to get it to work within Visual Studio but I was able to get it to work within `cmd`.

- Open `cmd`
- CD into the `src` folder
- Run the following commnad:
    ```
    dotnet publish Unluau.CLI -r win-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
    ```
